#ifndef MANAGE_MONITOR_MODE_IMPL_ADAPTER_H
#define MANAGE_MONITOR_MODE_IMPL_ADAPTER_H

#include <all.h>

Unit isolette_Monitor_Manage_Monitor_Mode_impl_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit isolette_Monitor_Manage_Monitor_Mode_impl_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit isolette_Monitor_Manage_Monitor_Mode_impl_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints isolette_Monitor_Manage_Monitor_Mode_impl_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
