#include <TempSensor_i_tcp_tempSensor_adapter.h>

Unit building_control_mixed_BuildingControl_TempSensor_i_tcp_tempSensor_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "TempSensor_i_tcp_tempSensor_adapter.c", "", "building_control_mixed_BuildingControl_TempSensor_i_tcp_tempSensor_adapter_initialiseArchitecture", 0);

  building_control_mixed_TempSensor_i_tcp_tempSensor_tempSensor_initialiseArchitecture(SF_LAST);
}

Unit building_control_mixed_BuildingControl_TempSensor_i_tcp_tempSensor_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "TempSensor_i_tcp_tempSensor_adapter.c", "", "building_control_mixed_BuildingControl_TempSensor_i_tcp_tempSensor_adapter_initialiseEntryPoint", 0);

  building_control_mixed_TempSensor_i_tcp_tempSensor_tempSensor_initialiseEntryPoint(SF_LAST);
}

Unit building_control_mixed_BuildingControl_TempSensor_i_tcp_tempSensor_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "TempSensor_i_tcp_tempSensor_adapter.c", "", "building_control_mixed_BuildingControl_TempSensor_i_tcp_tempSensor_adapter_computeEntryPoint", 0);

  building_control_mixed_TempSensor_i_tcp_tempSensor_tempSensor_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints building_control_mixed_BuildingControl_TempSensor_i_tcp_tempSensor_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "TempSensor_i_tcp_tempSensor_adapter.c", "", "building_control_mixed_BuildingControl_TempSensor_i_tcp_tempSensor_adapter_entryPoints", 0);

  return building_control_mixed_TempSensor_i_tcp_tempSensor_tempSensor_entryPoints(SF_LAST);
}
