#include <Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter.h>

Unit isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter.c", "", "isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter_initialiseArchitecture", 0);

  isolette_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_mat_initialiseArchitecture(SF_LAST);
}

Unit isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter.c", "", "isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter_initialiseEntryPoint", 0);

  isolette_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_mat_initialiseEntryPoint(SF_LAST);
}

Unit isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter.c", "", "isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter_computeEntryPoint", 0);

  isolette_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_mat_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter.c", "", "isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter_entryPoints", 0);

  return isolette_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_mat_entryPoints(SF_LAST);
}
