#ifndef MANAGE_ALARM_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_MANAGE_ALARM_MAT_ADAPTER_H
#define MANAGE_ALARM_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_MANAGE_ALARM_MAT_ADAPTER_H

#include <all.h>

Unit isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_mat_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
