#ifndef FAN_I_ADAPTER_H
#define FAN_I_ADAPTER_H

#include <all.h>

Unit building_control_gen_mixed_BuildingControl_Fan_i_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit building_control_gen_mixed_BuildingControl_Fan_i_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit building_control_gen_mixed_BuildingControl_Fan_i_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints building_control_gen_mixed_BuildingControl_Fan_i_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
