#include <Manage_Heat_Source_impl_adapter.h>

Unit isolette_Regulate_Manage_Heat_Source_impl_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Heat_Source_impl_adapter.c", "", "isolette_Regulate_Manage_Heat_Source_impl_adapter_initialiseArchitecture", 0);

  isolette_isolette_single_sensor_Instance_thermostat_regulate_temperature_manage_heat_source_mhst_mhst_initialiseArchitecture(SF_LAST);
}

Unit isolette_Regulate_Manage_Heat_Source_impl_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Heat_Source_impl_adapter.c", "", "isolette_Regulate_Manage_Heat_Source_impl_adapter_initialiseEntryPoint", 0);

  isolette_isolette_single_sensor_Instance_thermostat_regulate_temperature_manage_heat_source_mhst_mhst_initialiseEntryPoint(SF_LAST);
}

Unit isolette_Regulate_Manage_Heat_Source_impl_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Heat_Source_impl_adapter.c", "", "isolette_Regulate_Manage_Heat_Source_impl_adapter_computeEntryPoint", 0);

  isolette_isolette_single_sensor_Instance_thermostat_regulate_temperature_manage_heat_source_mhst_mhst_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints isolette_Regulate_Manage_Heat_Source_impl_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Heat_Source_impl_adapter.c", "", "isolette_Regulate_Manage_Heat_Source_impl_adapter_entryPoints", 0);

  return isolette_isolette_single_sensor_Instance_thermostat_regulate_temperature_manage_heat_source_mhst_mhst_entryPoints(SF_LAST);
}
