#include <TempControl_i_tcp_tempControl_adapter.h>

Unit building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "TempControl_i_tcp_tempControl_adapter.c", "", "building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl_adapter_initialiseArchitecture", 0);

  building_control_mixed_TempControl_i_tcp_tempControl_tempControl_initialiseArchitecture(SF_LAST);
}

Unit building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "TempControl_i_tcp_tempControl_adapter.c", "", "building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl_adapter_initialiseEntryPoint", 0);

  building_control_mixed_TempControl_i_tcp_tempControl_tempControl_initialiseEntryPoint(SF_LAST);
}

Unit building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "TempControl_i_tcp_tempControl_adapter.c", "", "building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl_adapter_computeEntryPoint", 0);

  building_control_mixed_TempControl_i_tcp_tempControl_tempControl_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "TempControl_i_tcp_tempControl_adapter.c", "", "building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl_adapter_entryPoints", 0);

  return building_control_mixed_TempControl_i_tcp_tempControl_tempControl_entryPoints(SF_LAST);
}
