#ifndef TEMPCONTROL_I_TCP_TEMPCONTROL_ADAPTER_H
#define TEMPCONTROL_I_TCP_TEMPCONTROL_ADAPTER_H

#include <all.h>

Unit building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
