#ifndef MANAGE_REGULATOR_MODE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_REGULATOR_MODE_MRMT_ADAPTER_H
#define MANAGE_REGULATOR_MODE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_REGULATOR_MODE_MRMT_ADAPTER_H

#include <all.h>

Unit isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
