#include <Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter.h>

Unit isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter.c", "", "isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter_initialiseArchitecture", 0);

  isolette_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_mrmt_initialiseArchitecture(SF_LAST);
}

Unit isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter.c", "", "isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter_initialiseEntryPoint", 0);

  isolette_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_mrmt_initialiseEntryPoint(SF_LAST);
}

Unit isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter.c", "", "isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter_computeEntryPoint", 0);

  isolette_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_mrmt_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter.c", "", "isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_adapter_entryPoints", 0);

  return isolette_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_mrmt_mrmt_entryPoints(SF_LAST);
}
