#ifndef MANAGE_MONITOR_INTERFACE_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_MANAGE_MONITOR_INTERFACE_MMIT_ADAPTER_H
#define MANAGE_MONITOR_INTERFACE_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_MANAGE_MONITOR_INTERFACE_MMIT_ADAPTER_H

#include <all.h>

Unit isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface_mmit_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface_mmit_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface_mmit_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface_mmit_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
