#include <Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_adapter.h>

Unit isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_adapter.c", "", "isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_adapter_initialiseArchitecture", 0);

  isolette_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_mrit_initialiseArchitecture(SF_LAST);
}

Unit isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_adapter.c", "", "isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_adapter_initialiseEntryPoint", 0);

  isolette_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_mrit_initialiseEntryPoint(SF_LAST);
}

Unit isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_adapter.c", "", "isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_adapter_computeEntryPoint", 0);

  isolette_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_mrit_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_adapter.c", "", "isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_adapter_entryPoints", 0);

  return isolette_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_mrit_mrit_entryPoints(SF_LAST);
}
