#ifndef OPERATOR_INTERFACE_THREAD_IMPL_OPERATOR_INTERFACE_OIP_OIT_ADAPTER_H
#define OPERATOR_INTERFACE_THREAD_IMPL_OPERATOR_INTERFACE_OIP_OIT_ADAPTER_H

#include <all.h>

Unit isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
