#include <operator_interface_thread_impl_operator_interface_oip_oit_adapter.h>

Unit isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "operator_interface_thread_impl_operator_interface_oip_oit_adapter.c", "", "isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_adapter_initialiseArchitecture", 0);

  isolette_operator_interface_thread_impl_operator_interface_oip_oit_oit_initialiseArchitecture(SF_LAST);
}

Unit isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "operator_interface_thread_impl_operator_interface_oip_oit_adapter.c", "", "isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_adapter_initialiseEntryPoint", 0);

  isolette_operator_interface_thread_impl_operator_interface_oip_oit_oit_initialiseEntryPoint(SF_LAST);
}

Unit isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "operator_interface_thread_impl_operator_interface_oip_oit_adapter.c", "", "isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_adapter_computeEntryPoint", 0);

  isolette_operator_interface_thread_impl_operator_interface_oip_oit_oit_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "operator_interface_thread_impl_operator_interface_oip_oit_adapter.c", "", "isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_adapter_entryPoints", 0);

  return isolette_operator_interface_thread_impl_operator_interface_oip_oit_oit_entryPoints(SF_LAST);
}
