#ifndef MANAGE_HEAT_SOURCE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_HEAT_SOURCE_MHST_ADAPTER_H
#define MANAGE_HEAT_SOURCE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_HEAT_SOURCE_MHST_ADAPTER_H

#include <all.h>

Unit isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source_mhst_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source_mhst_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source_mhst_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source_mhst_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
