#ifndef HEAT_SOURCE_IMPL_HEAT_SOURCE_CPI_HEAT_CONTROLLER_ADAPTER_H
#define HEAT_SOURCE_IMPL_HEAT_SOURCE_CPI_HEAT_CONTROLLER_ADAPTER_H

#include <all.h>

Unit isolette_Devices_Heat_Source_impl_heat_source_cpi_heat_controller_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit isolette_Devices_Heat_Source_impl_heat_source_cpi_heat_controller_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit isolette_Devices_Heat_Source_impl_heat_source_cpi_heat_controller_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints isolette_Devices_Heat_Source_impl_heat_source_cpi_heat_controller_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
