#ifndef TEMPERATURE_SENSOR_IMPL_TEMPERATURE_SENSOR_CPI_THERMOSTAT_ADAPTER_H
#define TEMPERATURE_SENSOR_IMPL_TEMPERATURE_SENSOR_CPI_THERMOSTAT_ADAPTER_H

#include <all.h>

Unit isolette_Devices_Temperature_Sensor_impl_temperature_sensor_cpi_thermostat_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit isolette_Devices_Temperature_Sensor_impl_temperature_sensor_cpi_thermostat_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit isolette_Devices_Temperature_Sensor_impl_temperature_sensor_cpi_thermostat_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints isolette_Devices_Temperature_Sensor_impl_temperature_sensor_cpi_thermostat_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
