#ifndef MANAGE_REGULATOR_INTERFACE_IMPL_ADAPTER_H
#define MANAGE_REGULATOR_INTERFACE_IMPL_ADAPTER_H

#include <all.h>

Unit isolette_Regulate_Manage_Regulator_Interface_impl_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit isolette_Regulate_Manage_Regulator_Interface_impl_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit isolette_Regulate_Manage_Regulator_Interface_impl_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints isolette_Regulate_Manage_Regulator_Interface_impl_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
