#ifndef TEMPCONTROL_I_TCP_TEMPCONTROL_API_H
#define TEMPCONTROL_I_TCP_TEMPCONTROL_API_H

#include <all.h>

// This file was auto-generated.  Do not edit

bool api_get_currentTemp__building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl(
  STACK_FRAME
  building_control_mixed_BuildingControl_Temperature_i value);

bool api_get_fanAck__building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl(
  STACK_FRAME
  building_control_mixed_BuildingControl_FanAck_Type *value);

bool api_get_setPoint__building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl(
  STACK_FRAME
  building_control_mixed_BuildingControl_SetPoint_i value);

void api_send_fanCmd__building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl(
  STACK_FRAME
  building_control_mixed_BuildingControl_FanCmd_Type value);

bool api_get_tempChanged__building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl(STACK_FRAME_ONLY);

void api_logInfo__building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl(
  STACK_FRAME
  String str);

void api_logDebug__building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl(
  STACK_FRAME
  String str);

void api_logError__building_control_mixed_BuildingControl_TempControl_i_tcp_tempControl(
  STACK_FRAME
  String str);

#endif
