#ifndef FAN_I_FP_FAN_ADAPTER_H
#define FAN_I_FP_FAN_ADAPTER_H

#include <all.h>

Unit b_TemperatureControl_Fan_i_fp_fan_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit b_TemperatureControl_Fan_i_fp_fan_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit b_TemperatureControl_Fan_i_fp_fan_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints b_TemperatureControl_Fan_i_fp_fan_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
