#include <Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_adapter.h>

Unit isolette_Monitor_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_adapter.c", "", "isolette_Monitor_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_adapter_initialiseArchitecture", 0);

  isolette_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_mmmt_initialiseArchitecture(SF_LAST);
}

Unit isolette_Monitor_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_adapter.c", "", "isolette_Monitor_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_adapter_initialiseEntryPoint", 0);

  isolette_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_mmmt_initialiseEntryPoint(SF_LAST);
}

Unit isolette_Monitor_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_adapter.c", "", "isolette_Monitor_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_adapter_computeEntryPoint", 0);

  isolette_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_mmmt_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints isolette_Monitor_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_adapter.c", "", "isolette_Monitor_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_adapter_entryPoints", 0);

  return isolette_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_mmmt_mmmt_entryPoints(SF_LAST);
}
